git:
  commit:
    signOff: true
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
    - colorArg: always
      command: delta --side-by-side --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  localBranchSortOrder: recency
os:
  editPreset: nvim
  openLink: >
    if [[ "$TERM" =~ ^(screen|tmux) ]]; then


      printf "\033Ptmux;\033\033]52;c;$(echo -n {{link}} | base64 -w 0)\a\033\\" > /dev/tty
    else


      printf "\033]52;c;$(echo -n {{link}} | base64 -w 0)\a" > /dev/tty
    fi

  copyToClipboardCmd: >
    if [[ "$TERM" =~ ^(screen|tmux) ]]; then


      printf "\033Ptmux;\033\033]52;c;$(echo -n {{text}} | base64 -w 0)\a\033\\" > /dev/tty
    else


      printf "\033]52;c;$(echo -n {{text}} | base64 -w 0)\a" > /dev/tty
    fi

gui:
  nerdFontsVersion: "3"
  switchTabsWithPanelJumpKeys: true
customCommands:
  - key: "U"
    command: "git submodule update --init --recursive"
    context: "localBranches, files"
    description: "Update submodules"
    loadingText: "Updating Submodules..."
    output: log
  - key: X
    description: "Copy/paste commits across repos"
    commandMenu:
    - key: c
      command: 'git format-patch --stdout {{.SelectedCommitRange.From}}^..{{.SelectedCommitRange.To}} | copy_osc52'
      context: commits, subCommits
      description: "Copy selected commits to clipboard"
    - key: v
      command: 'tmux refresh-client -l; sleep 0.2; tmux save-buffer - | git am'
      context: "commits"
      description: "Paste selected commits from clipboard"

promptToReturnFromSubprocess: false
