return {
  'stevearc/aerial.nvim',
  opts = {
    layout = {
      max_width = { 40, 0.2 },
      width = nil,
      min_width = 25,
    },
    keymaps = {
      ["?"] = "actions.show_help",
      ["<CR>"] = "actions.jump",
      ["<2-LeftMouse>"] = "actions.jump",
      ["<C-w>v"] = "actions.jump_vsplit",
      ["<C-w>h"] = "actions.jump_split",
      ["<C-v>"] = "false",
      ["<C-s>"] = "false",
      ["p"] = "actions.scroll",
      ["<C-j>"] = "actions.down_and_scroll",
      ["<C-k>"] = "actions.up_and_scroll",
      ["{"] = "false",
      ["}"] = "false",
      ["[["] = "false",
      ["]]"] = "false",
      ["q"] = "actions.close",
      ["o"] = "actions.tree_toggle",
      ["za"] = "false",
      ["O"] = "actions.tree_toggle_recursive",
      ["zA"] = "false",
      ["l"] = "false",
      ["zo"] = "false",
      ["L"] = "false",
      ["zO"] = "false",
      ["h"] = "false",
      ["zc"] = "false",
      ["H"] = "false",
      ["zC"] = "false",
      ["zr"] = "false",
      ["zR"] = "false",
      ["zm"] = "false",
      ["zM"] = "false",
      ["zx"] = "false",
      ["zX"] = "false",
    },
    autojump = false,
    filter_kind = false,
    highlight_on_hover = true,
  },
  keys = {
    { "<leader>o", "<cmd>AerialToggle<CR>", desc = "Toggle aerial outline" },
  },
  -- Optional dependencies
  dependencies = {
     "nvim-treesitter/nvim-treesitter",
     "nvim-tree/nvim-web-devicons"
  },
}
