# .bash_profile

# User specific environment and startup programs

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

export PATH
unset USERNAME

PS1='\[\e]133;D;$?\e\\\e]133;A\e\\\]\[\]\u@\h:\w> \[\e]133;B\e\\\]'
